kafkaPool: nav-prod
azure:
  enabled: true
  tenant: nav.no
env:
- name: SKJERMEDE_BASE_URL
  value: https://skjermede-personer-pip.intern.nav.no
- name: SKJERMEDE_OAUTH_SCOPE
  value: api://prod-gcp.yml.nom.skjermede-personer-pip/.default
