kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/azuread
  kvPath: /azuread/data/dev/creds/sparkel-medlemskap
env:
- name: KAFKA_CONSUMER_GROUP_ID
  value: tbd-sparkel-medlemskap-v1
- name: KAFKA_RAPID_TOPIC
  value: tbd.rapid.v1
- name: AZURE_TENANT_ID
  value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
- name: AZURE_TENANT_BASEURL
  value: https://login.microsoftonline.com
- name: MEDLEMSKAP_SCOPE
  value: api://496b0ded-cfdb-4430-b7b6-b568504de005/.default
