kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkelnorg
env:
- name: KAFKA_PREFER_ON_PREM
  value: "true"
- name: NORG2_BASE_URL
  value: https://app.adeo.no/norg2/api/v1
- name: PERSONV3_URL
  value: https://app.adeo.no/tpsws-aura/ws/Person/v3
- name: SECURITY_TOKEN_SERVICE_URL
  value: https://sts.adeo.no/SecurityTokenServiceProvider/
- name: KAFKA_BOOTSTRAP_SERVERS
  value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
- name: KAFKA_RAPID_TOPIC
  value: helse-rapid-v1
- name: KAFKA_CONSUMER_GROUP_ID
  value: sparkel-norg-v1
