kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelpersoninfo
env:
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: PDL_URL
  value: https://pdl-api.nais.preprod.local/graphql
- name: KAFKA_BOOTSTRAP_SERVERS
  value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
