kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkelpersoninfo
env:
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: PDL_URL
  value: https://pdl-api.nais.adeo.no/graphql
- name: KAFKA_BOOTSTRAP_SERVERS
  value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443,SASL_SSL://a01apvl00150.adeo.no:8443
