kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkeldkif
env:
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: DKIF_URL
  value: http://dkif.default.svc.nais.local

