kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelgosys
env:
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: OPPGAVE_URL
  value: https://oppgave-q1.dev.intern.nav.no

