kafkaPool: nav-prod
mountPaths:
  - mountPath: /var/run/secrets/nais.io/service_user
    kvPath: /serviceuser/data/prod/srvsparkelgosys
envFrom:
  - spre-gosys
env:
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: OPPGAVE_URL
  value: http://oppgave.default.svc.nais.local
