kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
limits:
  cpu: 2000m
azure:
  enabled: true
  tenant: trygdeetaten.no

accessPolicy:
  outbound:
    rules:
      - application: api-intern
        namespace: aap
        cluster: dev-gcp
env:
  - name: AAP_API_BASE_URL
    value: http://api-intern
  - name: ACCESS_TOKEN_SCOPE
    value: api://dev-gcp.aap.api-intern/.default
