kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
  tenant: nav.no

accessPolicy:
  outbound:
    rules:
      - application: api-intern
        namespace: aap
        cluster: prod-gcp
env:
  - name: AAP_API_BASE_URL
    value: http://api-intern.aap
  - name: ACCESS_TOKEN_SCOPE
    value: api://prod-gcp.aap.api-intern/.default
