kafkaPool: nav-prod
azure:
  enabled: true
env:
  - name: KODEVERK_BASE_URL
    value: http://kodeverk.default.svc.nais.local
  - name: ORGANISASJON_BASE_URL
    value: https://modapp.adeo.no/ereg/api
  - name: AAREG_BASE_URL_REST
    value: https://aareg-services.intern.nav.no/api
  - name: AAREG_OAUTH_SCOPE
    value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default