kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkelaareg
env:
- name: STS_BASE_SOAP_URL
  value: https://sts.adeo.no/SecurityTokenServiceProvider/
- name: KODEVERK_BASE_URL
  value: http://kodeverk.default.svc.nais.local
- name: ORGANISASJON_BASE_URL
  value: https://modapp.adeo.no/ereg/api/v1
- name: SOAP_ORGANISASJON_BASE_URL
  value: https://modapp.adeo.no/ereg/ws/OrganisasjonService/v5
- name: AAREG_BASE_URL_REST
  value: https://modapp.adeo.no/aareg-services/api
