kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkelinst
env:
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: INSTITUSJONSOPPHOLD_URL
  value: https://inst2.intern.nav.no
